"""Stable local error codes shared by API, jobs, workers, and diagnostics."""

from __future__ import annotations

import re
from enum import StrEnum

AUTHORIZATION_ERROR_RE = re.compile(r"(?i)\bauthorization\s*[:=]\s*bearer\s+\S+")
BEARER_ERROR_RE = re.compile(r"(?i)\bbearer\s+\S+")
HF_TOKEN_ERROR_RE = re.compile(r"(?i)\bhf_[a-z0-9]{8,}\b")
POSIX_PATH_ERROR_RE = re.compile(r"(?<![A-Za-z0-9:/])/(?:[^/\s]+/)+[^/\s]*")
WINDOWS_PATH_ERROR_RE = re.compile(r"(?i)\b[A-Z]:\\(?:[^\\\s]+\\)+[^\\\s]*")


class ErrorCode(StrEnum):
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_INVALID = "AUTH_INVALID"
    NON_LOOPBACK_CLIENT = "NON_LOOPBACK_CLIENT"
    INVALID_FILE_ID = "INVALID_FILE_ID"
    PATH_OUTSIDE_ALLOWED_ROOT = "PATH_OUTSIDE_ALLOWED_ROOT"
    UPLOAD_TOO_LARGE = "UPLOAD_TOO_LARGE"
    AUDIO_TOO_LONG = "AUDIO_TOO_LONG"
    UNSUPPORTED_MEDIA = "UNSUPPORTED_MEDIA"
    DECODE_LIMIT_EXCEEDED = "DECODE_LIMIT_EXCEEDED"
    JOB_STATE_CONFLICT = "JOB_STATE_CONFLICT"
    CHECKPOINT_RETRY_EXHAUSTED = "CHECKPOINT_RETRY_EXHAUSTED"
    SEGMENT_VERSION_CONFLICT = "SEGMENT_VERSION_CONFLICT"
    CANDIDATE_ALREADY_ADOPTED = "CANDIDATE_ALREADY_ADOPTED"
    CANDIDATE_TIMELINE_INVALID = "CANDIDATE_TIMELINE_INVALID"
    WORKER_CRASH = "WORKER_CRASH"
    WORKER_SOCKET_DISCONNECTED = "WORKER_SOCKET_DISCONNECTED"
    MICROPHONE_DISCONNECTED = "MICROPHONE_DISCONNECTED"
    GPU_OUT_OF_MEMORY = "GPU_OUT_OF_MEMORY"
    ALIGNMENT_FAILED = "ALIGNMENT_FAILED"
    WINDOW_DEDUP_CONFLICT = "WINDOW_DEDUP_CONFLICT"
    MODEL_INSTALL_NOT_USER_INITIATED = "MODEL_INSTALL_NOT_USER_INITIATED"
    MODEL_INSTALL_BLOCKED = "MODEL_INSTALL_BLOCKED"
    MODEL_REVISION_NOT_PINNED = "MODEL_REVISION_NOT_PINNED"
    MODEL_INTEGRITY_FAILED = "MODEL_INTEGRITY_FAILED"
    MODEL_HEALTH_CHECK_FAILED = "MODEL_HEALTH_CHECK_FAILED"
    MODEL_NOT_FULLY_INSTALLED = "MODEL_NOT_FULLY_INSTALLED"
    MODEL_DISK_SPACE_INSUFFICIENT = "MODEL_DISK_SPACE_INSUFFICIENT"
    MODEL_REVISION_ACTIVE = "MODEL_REVISION_ACTIVE"
    MEDIA_PROBE_FAILED = "MEDIA_PROBE_FAILED"
    MEDIA_DECODE_FAILED = "MEDIA_DECODE_FAILED"
    AUDIO_MASTER_INVALID = "AUDIO_MASTER_INVALID"
    AUDIO_TIMELINE_INVALID = "AUDIO_TIMELINE_INVALID"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class ClassScribeError(RuntimeError):
    def __init__(self, code: ErrorCode, detail: str) -> None:
        super().__init__(detail)
        self.code = code
        self.detail = detail


def public_error_detail(detail: str) -> str:
    """Remove credentials and full local paths before serializing an API error."""

    value = AUTHORIZATION_ERROR_RE.sub("[REDACTED]", detail)
    value = BEARER_ERROR_RE.sub("[REDACTED]", value)
    value = HF_TOKEN_ERROR_RE.sub("[REDACTED]", value)
    value = POSIX_PATH_ERROR_RE.sub("[LOCAL_PATH]", value)
    return WINDOWS_PATH_ERROR_RE.sub("[LOCAL_PATH]", value)
