"""initial schema

Revision ID: cd1f31626e3e
Revises: 
Create Date: 2026-09-03 21:36:15.347507
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cd1f31626e3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('manifest_version', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', 'cancelled', name='benchmark_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('hardware_json', sa.JSON(), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('ranking_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_runs'))
    )
    op.create_table('dictation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('language_mode', sa.Enum('zh', 'ja', 'en', 'auto_mixed', name='dictation_language', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('profile_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('active', 'committed', 'cancelled', 'failed', name='dictation_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('retain_history', sa.Boolean(), nullable=False),
    sa.Column('committed_text', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('retain_history = 1 OR audio_path IS NULL', name=op.f('ck_dictation_sessions_audio_requires_history_opt_in')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dictation_sessions'))
    )
    op.create_table('glossaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('course_id', sa.String(length=128), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossaries'))
    )
    with op.batch_alter_table('glossaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glossaries_course_id'), ['course_id'], unique=False)

    op.create_table('model_installations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('repository', sa.Text(), nullable=False),
    sa.Column('revision', sa.String(length=256), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('environment_json', sa.JSON(), nullable=False),
    sa.Column('measured_vram_mb', sa.Integer(), nullable=True),
    sa.Column('health_status', sa.Enum('unknown', 'healthy', 'unhealthy', 'missing', name='model_health', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_installations')),
    sa.UniqueConstraint('model_id', 'revision', name=op.f('uq_model_installations_model_id'))
    )
    with op.batch_alter_table('model_installations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_installations_model_id'), ['model_id'], unique=False)

    op.create_table('recordings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('duration_samples', sa.Integer(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('audio_qc_json', sa.JSON(), nullable=False),
    sa.CheckConstraint('channels > 0', name=op.f('ck_recordings_channels_positive')),
    sa.CheckConstraint('duration_samples >= 0', name=op.f('ck_recordings_duration_nonnegative')),
    sa.CheckConstraint('sample_rate > 0', name=op.f('ck_recordings_sample_rate_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recordings')),
    sa.UniqueConstraint('source_path', name=op.f('uq_recordings_source_path'))
    )
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.create_index('ix_recordings_sha256', ['source_sha256'], unique=False)

    op.create_table('benchmark_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('item_key', sa.String(length=256), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('model_revision', sa.String(length=256), nullable=False),
    sa.Column('gold_json', sa.JSON(), nullable=False),
    sa.Column('prediction_json', sa.JSON(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['benchmark_runs.id'], name=op.f('fk_benchmark_items_run_id_benchmark_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_items'))
    )
    with op.batch_alter_table('benchmark_items', schema=None) as batch_op:
        batch_op.create_index('ix_benchmark_items_model', ['run_id', 'model_id'], unique=False)

    op.create_table('glossary_terms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('glossary_id', sa.String(length=36), nullable=False),
    sa.Column('canonical', sa.Text(), nullable=False),
    sa.Column('reading', sa.Text(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('language', sa.Enum('zh', 'ja', 'en', 'auto_mixed', name='glossary_language', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['glossary_id'], ['glossaries.id'], name=op.f('fk_glossary_terms_glossary_id_glossaries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary_terms'))
    )
    with op.batch_alter_table('glossary_terms', schema=None) as batch_op:
        batch_op.create_index('ix_glossary_terms_lookup', ['glossary_id', 'language', 'canonical'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('language_mode', sa.Enum('zh', 'ja', 'en', 'auto_mixed', name='language_mode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('profile_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'paused', 'cancelling', 'cancelled', 'failed', 'completed', name='job_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('stage', sa.Enum('created', 'audio_import', 'audio_qc', 'vad', 'lid', 'structure', 'transcription', 'quality', 'postprocess', 'alignment', 'export', 'completed', name='job_stage', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('progress >= 0 AND progress <= 1', name=op.f('ck_jobs_progress_range')),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name=op.f('fk_jobs_recording_id_recordings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_recording_id'), ['recording_id'], unique=False)
        batch_op.create_index('ix_jobs_recovery', ['status', 'stage', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('job_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.Enum('created', 'audio_import', 'audio_qc', 'vad', 'lid', 'structure', 'transcription', 'quality', 'postprocess', 'alignment', 'export', 'completed', name='checkpoint_job_stage', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('checkpoint_key', sa.String(length=128), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'retryable', 'failed', 'cancelled', name='checkpoint_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('parameter_hash', sa.String(length=64), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_job_checkpoints_attempt_nonnegative')),
    sa.CheckConstraint('max_attempts >= 1', name=op.f('ck_job_checkpoints_max_attempts_positive')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_checkpoints_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_checkpoints')),
    sa.UniqueConstraint('job_id', 'stage', 'checkpoint_key', name=op.f('uq_job_checkpoints_job_id'))
    )
    with op.batch_alter_table('job_checkpoints', schema=None) as batch_op:
        batch_op.create_index('ix_job_checkpoints_resume', ['job_id', 'stage', 'status', 'position'], unique=False)

    op.create_table('language_spans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('start_sample', sa.Integer(), nullable=False),
    sa.Column('end_sample', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('zh', 'ja', 'en', 'auto_mixed', name='span_language', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence_raw', sa.Float(), nullable=False),
    sa.Column('decision_json', sa.JSON(), nullable=False),
    sa.CheckConstraint('end_sample >= start_sample', name=op.f('ck_language_spans_ordered_samples')),
    sa.CheckConstraint('start_sample >= 0', name=op.f('ck_language_spans_start_nonnegative')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_language_spans_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_language_spans'))
    )
    with op.batch_alter_table('language_spans', schema=None) as batch_op:
        batch_op.create_index('ix_language_spans_timeline', ['job_id', 'start_sample', 'end_sample'], unique=False)

    op.create_table('speaker_spans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('start_sample', sa.Integer(), nullable=False),
    sa.Column('end_sample', sa.Integer(), nullable=False),
    sa.Column('speaker_global_id', sa.String(length=128), nullable=False),
    sa.Column('speaker_local_id', sa.String(length=128), nullable=False),
    sa.Column('overlap', sa.Boolean(), nullable=False),
    sa.Column('source_model', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.CheckConstraint('end_sample >= start_sample', name=op.f('ck_speaker_spans_ordered_samples')),
    sa.CheckConstraint('start_sample >= 0', name=op.f('ck_speaker_spans_start_nonnegative')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_speaker_spans_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaker_spans'))
    )
    with op.batch_alter_table('speaker_spans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speaker_spans_speaker_global_id'), ['speaker_global_id'], unique=False)
        batch_op.create_index('ix_speaker_spans_timeline', ['job_id', 'start_sample', 'end_sample'], unique=False)

    op.create_table('speech_regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('start_sample', sa.Integer(), nullable=False),
    sa.Column('end_sample', sa.Integer(), nullable=False),
    sa.Column('vad_score', sa.Float(), nullable=False),
    sa.Column('acoustic_class', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.CheckConstraint('end_sample >= start_sample', name=op.f('ck_speech_regions_ordered_samples')),
    sa.CheckConstraint('start_sample >= 0', name=op.f('ck_speech_regions_start_nonnegative')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_speech_regions_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speech_regions'))
    )
    with op.batch_alter_table('speech_regions', schema=None) as batch_op:
        batch_op.create_index('ix_speech_regions_timeline', ['job_id', 'start_sample', 'end_sample'], unique=False)

    op.create_table('transcript_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('start_sample', sa.Integer(), nullable=False),
    sa.Column('end_sample', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.String(length=128), nullable=True),
    sa.Column('language', sa.Enum('zh', 'ja', 'en', 'auto_mixed', name='segment_language', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('faithful_text', sa.Text(), nullable=False),
    sa.Column('smart_corrected_text', sa.Text(), nullable=False),
    sa.Column('user_text', sa.Text(), nullable=True),
    sa.Column('auto_final_source', sa.String(length=128), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('timing_quality', sa.Enum('structure', 'native', 'aligned', 'invalid', name='timing_quality', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('review_status', sa.Enum('auto', 'needs_review', 'reviewed', name='review_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_sample >= start_sample', name=op.f('ck_transcript_segments_ordered_samples')),
    sa.CheckConstraint('start_sample >= 0', name=op.f('ck_transcript_segments_start_nonnegative')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_transcript_segments_version_positive')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_transcript_segments_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_segments'))
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index('ix_transcript_segments_timeline', ['job_id', 'start_sample', 'end_sample'], unique=False)

    op.create_table('asr_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('model_revision', sa.String(length=256), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('confidence_raw', sa.Float(), nullable=True),
    sa.Column('confidence_calibrated', sa.Float(), nullable=True),
    sa.Column('quality_features_json', sa.JSON(), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=False),
    sa.Column('decode_config_json', sa.JSON(), nullable=False),
    sa.Column('inference_metrics_json', sa.JSON(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('is_adopted', sa.Boolean(), nullable=False),
    sa.Column('supersedes_candidate_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], name=op.f('fk_asr_candidates_segment_id_transcript_segments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_candidate_id'], ['asr_candidates.id'], name=op.f('fk_asr_candidates_supersedes_candidate_id_asr_candidates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asr_candidates'))
    )
    with op.batch_alter_table('asr_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_asr_candidates_active', ['segment_id', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_asr_candidates_is_adopted'), ['is_adopted'], unique=False)
        batch_op.create_index('ix_asr_candidates_model', ['segment_id', 'model_id', 'model_revision'], unique=False)

    op.create_table('decision_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('rule_version', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], name=op.f('fk_decision_events_segment_id_transcript_segments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_events'))
    )
    with op.batch_alter_table('decision_events', schema=None) as batch_op:
        batch_op.create_index('ix_decision_events_segment_created', ['segment_id', 'created_at'], unique=False)

    op.create_table('token_spans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('start_sample', sa.Integer(), nullable=False),
    sa.Column('end_sample', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('normalized_token', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.CheckConstraint('end_sample >= start_sample', name=op.f('ck_token_spans_ordered_samples')),
    sa.CheckConstraint('start_sample >= 0', name=op.f('ck_token_spans_start_nonnegative')),
    sa.ForeignKeyConstraint(['candidate_id'], ['asr_candidates.id'], name=op.f('fk_token_spans_candidate_id_asr_candidates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], name=op.f('fk_token_spans_segment_id_transcript_segments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_spans'))
    )
    with op.batch_alter_table('token_spans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_spans_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index('ix_token_spans_timeline', ['segment_id', 'start_sample', 'end_sample'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_spans', schema=None) as batch_op:
        batch_op.drop_index('ix_token_spans_timeline')
        batch_op.drop_index(batch_op.f('ix_token_spans_candidate_id'))

    op.drop_table('token_spans')
    with op.batch_alter_table('decision_events', schema=None) as batch_op:
        batch_op.drop_index('ix_decision_events_segment_created')

    op.drop_table('decision_events')
    with op.batch_alter_table('asr_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_asr_candidates_model')
        batch_op.drop_index(batch_op.f('ix_asr_candidates_is_adopted'))
        batch_op.drop_index('ix_asr_candidates_active')

    op.drop_table('asr_candidates')
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index('ix_transcript_segments_timeline')

    op.drop_table('transcript_segments')
    with op.batch_alter_table('speech_regions', schema=None) as batch_op:
        batch_op.drop_index('ix_speech_regions_timeline')

    op.drop_table('speech_regions')
    with op.batch_alter_table('speaker_spans', schema=None) as batch_op:
        batch_op.drop_index('ix_speaker_spans_timeline')
        batch_op.drop_index(batch_op.f('ix_speaker_spans_speaker_global_id'))

    op.drop_table('speaker_spans')
    with op.batch_alter_table('language_spans', schema=None) as batch_op:
        batch_op.drop_index('ix_language_spans_timeline')

    op.drop_table('language_spans')
    with op.batch_alter_table('job_checkpoints', schema=None) as batch_op:
        batch_op.drop_index('ix_job_checkpoints_resume')

    op.drop_table('job_checkpoints')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index('ix_jobs_recovery')
        batch_op.drop_index(batch_op.f('ix_jobs_recording_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('glossary_terms', schema=None) as batch_op:
        batch_op.drop_index('ix_glossary_terms_lookup')

    op.drop_table('glossary_terms')
    with op.batch_alter_table('benchmark_items', schema=None) as batch_op:
        batch_op.drop_index('ix_benchmark_items_model')

    op.drop_table('benchmark_items')
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_index('ix_recordings_sha256')

    op.drop_table('recordings')
    with op.batch_alter_table('model_installations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_installations_model_id'))

    op.drop_table('model_installations')
    with op.batch_alter_table('glossaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glossaries_course_id'))

    op.drop_table('glossaries')
    op.drop_table('dictation_sessions')
    op.drop_table('benchmark_runs')
    # ### end Alembic commands ###
