"""add structure evidence and speaker display names

Revision ID: eeec80ee63cf
Revises: cd1f31626e3e
Create Date: 2026-09-04 00:32:21.567283
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eeec80ee63cf'
down_revision: Union[str, Sequence[str], None] = 'cd1f31626e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker_display_names',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('speaker_global_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('identity_scope', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("identity_scope = 'job'", name=op.f('ck_speaker_display_names_speaker_identity_job_scoped')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_speaker_display_names_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaker_display_names')),
    sa.UniqueConstraint('job_id', 'speaker_global_id', name='uq_speaker_display_name')
    )
    op.create_table('structure_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('window_ordinal', sa.Integer(), nullable=False),
    sa.Column('start_sample', sa.Integer(), nullable=False),
    sa.Column('end_sample', sa.Integer(), nullable=False),
    sa.Column('speaker_global_id', sa.String(length=128), nullable=True),
    sa.Column('speaker_local_id', sa.String(length=128), nullable=True),
    sa.Column('coarse_text', sa.Text(), nullable=False),
    sa.Column('acoustic_events_json', sa.JSON(), nullable=False),
    sa.Column('overlap', sa.Boolean(), nullable=False),
    sa.Column('exclusive', sa.Boolean(), nullable=False),
    sa.Column('fallback', sa.Boolean(), nullable=False),
    sa.Column('source_model', sa.String(length=128), nullable=False),
    sa.Column('source_revision', sa.String(length=256), nullable=False),
    sa.Column('confidence_raw', sa.Float(), nullable=True),
    sa.Column('selection_score', sa.Float(), nullable=False),
    sa.Column('text_role', sa.String(length=128), nullable=False),
    sa.Column('adopted_as_final', sa.Boolean(), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('adopted_as_final = 0', name=op.f('ck_structure_segments_coarse_text_never_final')),
    sa.CheckConstraint('end_sample > start_sample', name=op.f('ck_structure_segments_ordered_samples')),
    sa.CheckConstraint('selection_score >= 0 AND selection_score <= 1', name=op.f('ck_structure_segments_selection_score_range')),
    sa.CheckConstraint('start_sample >= 0', name=op.f('ck_structure_segments_start_nonnegative')),
    sa.CheckConstraint('window_ordinal >= 0', name=op.f('ck_structure_segments_window_ordinal_nonnegative')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_structure_segments_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_structure_segments')),
    sa.UniqueConstraint('job_id', 'window_ordinal', 'start_sample', 'end_sample', 'source_model', 'source_revision', name='uq_structure_segment_source')
    )
    with op.batch_alter_table('structure_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_structure_segments_speaker_global_id'), ['speaker_global_id'], unique=False)
        batch_op.create_index('ix_structure_segments_timeline', ['job_id', 'start_sample', 'end_sample'], unique=False)

    with op.batch_alter_table('speaker_spans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('window_ordinal', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('source_revision', sa.String(length=256), server_default='0000000000000000000000000000000000000000', nullable=False))
        batch_op.add_column(sa.Column('provenance_json', sa.JSON(), server_default='{}', nullable=False))
        batch_op.create_check_constraint(batch_op.f('ck_speaker_spans_window_ordinal_nonnegative'), 'window_ordinal >= 0')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speaker_spans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_speaker_spans_window_ordinal_nonnegative'), type_='check')
        batch_op.drop_column('provenance_json')
        batch_op.drop_column('source_revision')
        batch_op.drop_column('window_ordinal')

    with op.batch_alter_table('structure_segments', schema=None) as batch_op:
        batch_op.drop_index('ix_structure_segments_timeline')
        batch_op.drop_index(batch_op.f('ix_structure_segments_speaker_global_id'))

    op.drop_table('structure_segments')
    op.drop_table('speaker_display_names')
    # ### end Alembic commands ###
